# Generated by Django 4.1.7 on 2023-09-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('GamersSFU', '0002_alter_zipfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Стрыницы игр',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageFile', models.FileField(upload_to='./static/img/')),
            ],
            options={
                'verbose_name': 'Жанры игр',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Жанры игр',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='zipfile',
            options={'ordering': ['id'], 'verbose_name': 'Файлы игр'},
        ),
        migrations.RenameField(
            model_name='zipfile',
            old_name='file',
            new_name='File',
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('Login', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='GamePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GamersSFU.game')),
                ('GameImage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GamersSFU.gameimage')),
            ],
            options={
                'verbose_name': 'Игры связанные с изображениями',
            },
        ),
        migrations.CreateModel(
            name='GameGanre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GamersSFU.game')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GamersSFU.genre')),
            ],
            options={
                'verbose_name': 'Игры связанные с жанрами',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='Developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='GameFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamersSFU.zipfile'),
        ),
    ]
