# Generated by Django 4.1.7 on 2023-09-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamersSFU', '0004_alter_gameimage_options_alter_game_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfile',
            old_name='File',
            new_name='GameFile',
        ),
    ]
