# Generated by Django 4.2.6 on 2023-10-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamersSFU', '0007_alter_gameico_imagefile_alter_gameimage_imagefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameico',
            options={'ordering': ['id'], 'verbose_name': 'иконки игр'},
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='role',
        ),
    ]
