# Generated by Django 4.1.7 on 2023-09-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamersSFU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file',
            field=models.FileField(upload_to='./static/zip_files/'),
        ),
    ]
